app:
  jwt-expiration: 1D
  jwt-secret: thisisagreatandlargesecretkeybutithinkitshouldbelarger
  public-urls:
    - "/h2-console/**"
    - "/swagger-ui.html**"
    - "/v3/**"
    - "/swagger-ui/**"
    - "/api/public/**"
server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./db/new_spa_db;AUTO_SERVER=TRUE
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
